import TripDetailsAddPlacesModal from './TripDetailsAddPlacesModal';
import TripDetailsAddFoodModal from './TripDetailsAddFoodModal';
import TripDetailsAddStaysModal from './TripDetailsAddStaysModal';
import TripDetailsAddExperiencesModal from './TripDetailsAddExperiencesModal';
import TripDetailsAddCustomExperienceModal from './TripDetailsAddCustomExperienceModal';
import TripDetailsAddCustomPlaceModal from './TripDetailsAddCustomPlaceModal';
import TripDetailsAddCustomFoodModal from './TripDetailsAddCustomFoodModal';

export default function TripDetailsDiscoveryModals(props) {
  const {
    addPlacesOpen,
    trip,
    days,
    cityQuery,
    destinationLabel,
    mapCenter,
    allDayNums,
    placeDetailsView,
    setPlaceDetailsView,
    itineraryDetailsView,
    selectedPlaceMarkerId,
    setSelectedPlaceMarkerId,
    filteredPlaces,
    addEntireItineraryToTrip,
    openItineraryPlaceDetails,
    openAddToTripFromMapMarker,
    openAddPlacesDetailsFromMapMarker,
    resetMapDays,
    setMapDayFilterOpen,
    discoveryError,
    discoveryLoading,
    placeSearchQuery,
    setPlaceSearchQuery,
    pagedPlaces,
    addPlacesPage,
    setAddPlacesPage,
    addPlacesTotalPages,
    placeSortBy,
    setPlaceSortBy,
    addPlacesDay,
    setCustomPlaceName,
    setCustomPlaceAddress,
    setCustomPlaceAddressSelection,
    setCustomPlaceAddressSuggestionsOpen,
    setCustomPlaceDateKey,
    setAddCustomPlaceOpen,
    placeDetailsTab,
    setPlaceDetailsTab,
    tripExpenseItems,
    setAddToTripItem,
    setAddToTripDate,
    setAddToTripStartTime,
    setAddToTripDurationHrs,
    setAddToTripDurationMins,
    setAddToTripNotes,
    setAddToTripCost,
    setAddToTripExternalLink,
    setAddToTripTravelDocs,
    setAddToTripModalOpen,
    onCloseAddPlacesBackdrop,
    onCloseAddPlacesItineraryHeader,
    onCloseAddPlacesListHeader,
    onCloseAddPlacesPlaceDetailHeader,
    addFoodOpen,
    filteredFoods,
    foodDetailsView,
    setFoodDetailsView,
    foodDetailsTab,
    setFoodDetailsTab,
    foodSearchQuery,
    setFoodSearchQuery,
    foodDietaryFilter,
    setFoodDietaryFilter,
    foodSortBy,
    setFoodSortBy,
    addFoodDay,
    discoveryData,
    setCustomFoodName,
    setCustomFoodAddress,
    setCustomFoodAddressSelection,
    setCustomFoodAddressSuggestionsOpen,
    setCustomFoodDateKey,
    setAddCustomFoodOpen,
    onCloseFoodBackdrop,
    onCloseFoodListHeader,
    onBackFoodDetail,
    addStaysOpen,
    filteredStays,
    stayTypeOptions,
    stayDetailsView,
    setStayDetailsView,
    stayDetailsTab,
    setStayDetailsTab,
    staySearchQuery,
    setStaySearchQuery,
    stayTypeFilter,
    setStayTypeFilter,
    stayStarFilter,
    setStayStarFilter,
    staySortBy,
    setStaySortBy,
    currency,
    exchangeRates,
    setEditPlaceItem,
    openAddStayToTrip,
    openStayBookingModal,
    onCloseStayBackdrop,
    onCloseStayListHeader,
    onBackStayDetail,
    addExperiencesOpen,
    filteredExperiences,
    experienceDetailsView,
    setExperienceDetailsView,
    experienceDetailsTab,
    setExperienceDetailsTab,
    experienceSearchQuery,
    setExperienceSearchQuery,
    experienceTypeFilter,
    setExperienceTypeFilter,
    experiencePriceRange,
    setExperiencePriceRange,
    experienceDurationFilter,
    setExperienceDurationFilter,
    experienceSortBy,
    setExperienceSortBy,
    addExperiencesDay,
    setBookingExperience,
    setBookingOption,
    setBookingDate,
    setBookingStartTime,
    setBookingTravellers,
    setBookingNotes,
    setExperienceBookingModalOpen,
    setCustomExperienceName,
    setCustomExperienceType,
    setCustomExperienceAddress,
    setCustomExperienceDateKey,
    setCustomExperienceStartTime,
    setCustomExperienceDurationHrs,
    setCustomExperienceDurationMins,
    setCustomExperienceNote,
    setCustomExperienceCost,
    setCustomExperienceExternalLink,
    setCustomExperienceTravelDocs,
    setAddCustomExperienceOpen,
    onCloseExperienceModal,
    onBackExperienceDetail,
    addCustomExperienceOpen,
    onCloseAddCustomExperience,
    handleAddCustomExperienceSubmit,
    customExperienceName,
    customExperienceType,
    customExperienceAddress,
    customExperienceDateKey,
    customExperienceStartTime,
    customExperienceDurationHrs,
    customExperienceDurationMins,
    customExperienceNote,
    customExperienceCost,
    customExperienceExternalLink,
    customExperienceTravelDocs,
    addCustomPlaceOpen,
    onCloseAddCustomPlace,
    handleAddCustomPlaceSubmit,
    customPlaceName,
    customPlaceAddress,
    customPlaceAddressSuggestionsOpen,
    customPlaceDateKey,
    customPlaceStartTime,
    setCustomPlaceStartTime,
    customPlaceDurationHrs,
    setCustomPlaceDurationHrs,
    customPlaceDurationMins,
    setCustomPlaceDurationMins,
    customPlaceNote,
    setCustomPlaceNote,
    customPlaceCost,
    setCustomPlaceCost,
    customPlaceImage,
    setCustomPlaceImage,
    customPlaceTravelDocs,
    setCustomPlaceTravelDocs,
    addCustomFoodOpen,
    onCloseAddCustomFood,
    handleAddCustomFoodSubmit,
    customFoodName,
    customFoodAddress,
    customFoodAddressSuggestionsOpen,
    customFoodDateKey,
    customFoodStartTime,
    setCustomFoodStartTime,
    customFoodDurationHrs,
    setCustomFoodDurationHrs,
    customFoodDurationMins,
    setCustomFoodDurationMins,
    customFoodNote,
    setCustomFoodNote,
    customFoodCost,
    setCustomFoodCost,
    customFoodImage,
    setCustomFoodImage,
    customFoodTravelDocs,
    setCustomFoodTravelDocs,
  } = props;

  return (
    <>
      {addPlacesOpen && (
        <TripDetailsAddPlacesModal
          trip={trip}
          days={days}
          cityQuery={cityQuery}
          destinationLabel={destinationLabel}
          mapCenter={mapCenter}
          allDayNums={allDayNums}
          placeDetailsView={placeDetailsView}
          setPlaceDetailsView={setPlaceDetailsView}
          itineraryDetailsView={itineraryDetailsView}
          selectedPlaceMarkerId={selectedPlaceMarkerId}
          setSelectedPlaceMarkerId={setSelectedPlaceMarkerId}
          filteredPlaces={filteredPlaces}
          addEntireItineraryToTrip={addEntireItineraryToTrip}
          openItineraryPlaceDetails={openItineraryPlaceDetails}
          openAddToTripFromMapMarker={openAddToTripFromMapMarker}
          openAddPlacesDetailsFromMapMarker={openAddPlacesDetailsFromMapMarker}
          resetMapDays={resetMapDays}
          setMapDayFilterOpen={setMapDayFilterOpen}
          discoveryError={discoveryError}
          discoveryLoading={discoveryLoading}
          placeSearchQuery={placeSearchQuery}
          setPlaceSearchQuery={setPlaceSearchQuery}
          pagedPlaces={pagedPlaces}
          addPlacesPage={addPlacesPage}
          setAddPlacesPage={setAddPlacesPage}
          addPlacesTotalPages={addPlacesTotalPages}
          placeSortBy={placeSortBy}
          setPlaceSortBy={setPlaceSortBy}
          addPlacesDay={addPlacesDay}
          setCustomPlaceName={setCustomPlaceName}
          setCustomPlaceAddress={setCustomPlaceAddress}
          setCustomPlaceAddressSelection={setCustomPlaceAddressSelection}
          setCustomPlaceAddressSuggestionsOpen={setCustomPlaceAddressSuggestionsOpen}
          setCustomPlaceDateKey={setCustomPlaceDateKey}
          setAddCustomPlaceOpen={setAddCustomPlaceOpen}
          placeDetailsTab={placeDetailsTab}
          setPlaceDetailsTab={setPlaceDetailsTab}
          tripExpenseItems={tripExpenseItems}
          setAddToTripItem={setAddToTripItem}
          setAddToTripDate={setAddToTripDate}
          setAddToTripStartTime={setAddToTripStartTime}
          setAddToTripDurationHrs={setAddToTripDurationHrs}
          setAddToTripDurationMins={setAddToTripDurationMins}
          setAddToTripNotes={setAddToTripNotes}
          setAddToTripCost={setAddToTripCost}
          setAddToTripExternalLink={setAddToTripExternalLink}
          setAddToTripTravelDocs={setAddToTripTravelDocs}
          setAddToTripModalOpen={setAddToTripModalOpen}
          onCloseBackdrop={onCloseAddPlacesBackdrop}
          onCloseItineraryHeader={onCloseAddPlacesItineraryHeader}
          onCloseListHeader={onCloseAddPlacesListHeader}
          onClosePlaceDetailHeader={onCloseAddPlacesPlaceDetailHeader}
        />
      )}
      {addFoodOpen && (
        <TripDetailsAddFoodModal
          trip={trip}
          days={days}
          cityQuery={cityQuery}
          destinationLabel={destinationLabel}
          mapCenter={mapCenter}
          allDayNums={allDayNums}
          filteredFoods={filteredFoods}
          foodDetailsView={foodDetailsView}
          setFoodDetailsView={setFoodDetailsView}
          foodDetailsTab={foodDetailsTab}
          setFoodDetailsTab={setFoodDetailsTab}
          foodSearchQuery={foodSearchQuery}
          setFoodSearchQuery={setFoodSearchQuery}
          foodDietaryFilter={foodDietaryFilter}
          setFoodDietaryFilter={setFoodDietaryFilter}
          foodSortBy={foodSortBy}
          setFoodSortBy={setFoodSortBy}
          addFoodDay={addFoodDay}
          discoveryError={discoveryError}
          discoveryLoading={discoveryLoading}
          discoveryData={discoveryData}
          setCustomFoodName={setCustomFoodName}
          setCustomFoodAddress={setCustomFoodAddress}
          setCustomFoodAddressSelection={setCustomFoodAddressSelection}
          setCustomFoodAddressSuggestionsOpen={setCustomFoodAddressSuggestionsOpen}
          setCustomFoodDateKey={setCustomFoodDateKey}
          setAddCustomFoodOpen={setAddCustomFoodOpen}
          tripExpenseItems={tripExpenseItems}
          setAddToTripItem={setAddToTripItem}
          setAddToTripDate={setAddToTripDate}
          setAddToTripStartTime={setAddToTripStartTime}
          setAddToTripDurationHrs={setAddToTripDurationHrs}
          setAddToTripDurationMins={setAddToTripDurationMins}
          setAddToTripNotes={setAddToTripNotes}
          setAddToTripCost={setAddToTripCost}
          setAddToTripExternalLink={setAddToTripExternalLink}
          setAddToTripTravelDocs={setAddToTripTravelDocs}
          setAddToTripModalOpen={setAddToTripModalOpen}
          openAddToTripFromMapMarker={openAddToTripFromMapMarker}
          openAddPlacesDetailsFromMapMarker={openAddPlacesDetailsFromMapMarker}
          resetMapDays={resetMapDays}
          setMapDayFilterOpen={setMapDayFilterOpen}
          onCloseFoodBackdrop={onCloseFoodBackdrop}
          onCloseFoodListHeader={onCloseFoodListHeader}
          onBackFoodDetail={onBackFoodDetail}
        />
      )}
      {addStaysOpen && (
        <TripDetailsAddStaysModal
          trip={trip}
          days={days}
          cityQuery={cityQuery}
          destinationLabel={destinationLabel}
          allDayNums={allDayNums}
          filteredStays={filteredStays}
          stayTypeOptions={stayTypeOptions}
          stayDetailsView={stayDetailsView}
          setStayDetailsView={setStayDetailsView}
          stayDetailsTab={stayDetailsTab}
          setStayDetailsTab={setStayDetailsTab}
          staySearchQuery={staySearchQuery}
          setStaySearchQuery={setStaySearchQuery}
          stayTypeFilter={stayTypeFilter}
          setStayTypeFilter={setStayTypeFilter}
          stayStarFilter={stayStarFilter}
          setStayStarFilter={setStayStarFilter}
          staySortBy={staySortBy}
          setStaySortBy={setStaySortBy}
          discoveryError={discoveryError}
          discoveryLoading={discoveryLoading}
          discoveryData={discoveryData}
          currency={currency}
          exchangeRates={exchangeRates}
          setEditPlaceItem={setEditPlaceItem}
          openAddStayToTrip={openAddStayToTrip}
          openStayBookingModal={openStayBookingModal}
          onCloseStayBackdrop={onCloseStayBackdrop}
          onCloseStayListHeader={onCloseStayListHeader}
          onBackStayDetail={onBackStayDetail}
        />
      )}

      {addExperiencesOpen && (
        <TripDetailsAddExperiencesModal
          trip={trip}
          days={days}
          cityQuery={cityQuery}
          destinationLabel={destinationLabel}
          mapCenter={mapCenter}
          allDayNums={allDayNums}
          filteredExperiences={filteredExperiences}
          experienceDetailsView={experienceDetailsView}
          setExperienceDetailsView={setExperienceDetailsView}
          experienceDetailsTab={experienceDetailsTab}
          setExperienceDetailsTab={setExperienceDetailsTab}
          experienceSearchQuery={experienceSearchQuery}
          setExperienceSearchQuery={setExperienceSearchQuery}
          experienceTypeFilter={experienceTypeFilter}
          setExperienceTypeFilter={setExperienceTypeFilter}
          experiencePriceRange={experiencePriceRange}
          setExperiencePriceRange={setExperiencePriceRange}
          experienceDurationFilter={experienceDurationFilter}
          setExperienceDurationFilter={setExperienceDurationFilter}
          experienceSortBy={experienceSortBy}
          setExperienceSortBy={setExperienceSortBy}
          addExperiencesDay={addExperiencesDay}
          discoveryError={discoveryError}
          discoveryLoading={discoveryLoading}
          discoveryData={discoveryData}
          tripExpenseItems={tripExpenseItems}
          setBookingExperience={setBookingExperience}
          setBookingOption={setBookingOption}
          setBookingDate={setBookingDate}
          setBookingStartTime={setBookingStartTime}
          setBookingTravellers={setBookingTravellers}
          setBookingNotes={setBookingNotes}
          setExperienceBookingModalOpen={setExperienceBookingModalOpen}
          openAddToTripFromMapMarker={openAddToTripFromMapMarker}
          openAddPlacesDetailsFromMapMarker={openAddPlacesDetailsFromMapMarker}
          resetMapDays={resetMapDays}
          setMapDayFilterOpen={setMapDayFilterOpen}
          setCustomExperienceName={setCustomExperienceName}
          setCustomExperienceType={setCustomExperienceType}
          setCustomExperienceAddress={setCustomExperienceAddress}
          setCustomExperienceDateKey={setCustomExperienceDateKey}
          setCustomExperienceStartTime={setCustomExperienceStartTime}
          setCustomExperienceDurationHrs={setCustomExperienceDurationHrs}
          setCustomExperienceDurationMins={setCustomExperienceDurationMins}
          setCustomExperienceNote={setCustomExperienceNote}
          setCustomExperienceCost={setCustomExperienceCost}
          setCustomExperienceExternalLink={setCustomExperienceExternalLink}
          setCustomExperienceTravelDocs={setCustomExperienceTravelDocs}
          setAddCustomExperienceOpen={setAddCustomExperienceOpen}
          onCloseExperienceBackdrop={onCloseExperienceModal}
          onCloseExperienceListHeader={onCloseExperienceModal}
          onBackExperienceDetail={onBackExperienceDetail}
        />
      )}

      {addCustomExperienceOpen && (
        <TripDetailsAddCustomExperienceModal
          onClose={onCloseAddCustomExperience}
          onSubmit={handleAddCustomExperienceSubmit}
          days={days}
          tripExpenseItems={tripExpenseItems}
          currency={currency}
          customExperienceName={customExperienceName}
          setCustomExperienceName={setCustomExperienceName}
          customExperienceType={customExperienceType}
          setCustomExperienceType={setCustomExperienceType}
          customExperienceAddress={customExperienceAddress}
          setCustomExperienceAddress={setCustomExperienceAddress}
          customExperienceDateKey={customExperienceDateKey}
          setCustomExperienceDateKey={setCustomExperienceDateKey}
          customExperienceStartTime={customExperienceStartTime}
          setCustomExperienceStartTime={setCustomExperienceStartTime}
          customExperienceDurationHrs={customExperienceDurationHrs}
          setCustomExperienceDurationHrs={setCustomExperienceDurationHrs}
          customExperienceDurationMins={customExperienceDurationMins}
          setCustomExperienceDurationMins={setCustomExperienceDurationMins}
          customExperienceNote={customExperienceNote}
          setCustomExperienceNote={setCustomExperienceNote}
          customExperienceCost={customExperienceCost}
          setCustomExperienceCost={setCustomExperienceCost}
          customExperienceExternalLink={customExperienceExternalLink}
          setCustomExperienceExternalLink={setCustomExperienceExternalLink}
          customExperienceTravelDocs={customExperienceTravelDocs}
          setCustomExperienceTravelDocs={setCustomExperienceTravelDocs}
        />
      )}

      {addCustomPlaceOpen && (
        <TripDetailsAddCustomPlaceModal
          trip={trip}
          days={days}
          onClose={onCloseAddCustomPlace}
          onSubmit={handleAddCustomPlaceSubmit}
          customPlaceName={customPlaceName}
          setCustomPlaceName={setCustomPlaceNameState}
          customPlaceAddress={customPlaceAddress}
          setCustomPlaceAddress={setCustomPlaceAddressState}
          setCustomPlaceAddressSelection={setCustomPlaceAddressSelection}
          customPlaceAddressSuggestionsOpen={customPlaceAddressSuggestionsOpen}
          setCustomPlaceAddressSuggestionsOpen={setCustomPlaceAddressSuggestionsOpen}
          customPlaceDateKey={customPlaceDateKey}
          setCustomPlaceDateKey={setCustomPlaceDateKey}
          customPlaceStartTime={customPlaceStartTime}
          setCustomPlaceStartTime={setCustomPlaceStartTime}
          customPlaceDurationHrs={customPlaceDurationHrs}
          setCustomPlaceDurationHrs={setCustomPlaceDurationHrs}
          customPlaceDurationMins={customPlaceDurationMins}
          setCustomPlaceDurationMins={setCustomPlaceDurationMins}
          customPlaceNote={customPlaceNote}
          setCustomPlaceNote={setCustomPlaceNote}
          customPlaceCost={customPlaceCost}
          setCustomPlaceCost={setCustomPlaceCost}
          customPlaceImage={customPlaceImage}
          setCustomPlaceImage={setCustomPlaceImage}
          customPlaceTravelDocs={customPlaceTravelDocs}
          setCustomPlaceTravelDocs={setCustomPlaceTravelDocs}
          currency={currency}
        />
      )}

      {addCustomFoodOpen && (
        <TripDetailsAddCustomFoodModal
          trip={trip}
          days={days}
          onClose={onCloseAddCustomFood}
          onSubmit={handleAddCustomFoodSubmit}
          customFoodName={customFoodName}
          setCustomFoodName={setCustomFoodName}
          customFoodAddress={customFoodAddress}
          setCustomFoodAddress={setCustomFoodAddress}
          setCustomFoodAddressSelection={setCustomFoodAddressSelection}
          customFoodAddressSuggestionsOpen={customFoodAddressSuggestionsOpen}
          setCustomFoodAddressSuggestionsOpen={setCustomFoodAddressSuggestionsOpen}
          customFoodDateKey={customFoodDateKey}
          setCustomFoodDateKey={setCustomFoodDateKey}
          customFoodStartTime={customFoodStartTime}
          setCustomFoodStartTime={setCustomFoodStartTime}
          customFoodDurationHrs={customFoodDurationHrs}
          setCustomFoodDurationHrs={setCustomFoodDurationHrs}
          customFoodDurationMins={customFoodDurationMins}
          setCustomFoodDurationMins={setCustomFoodDurationMins}
          customFoodNote={customFoodNote}
          setCustomFoodNote={setCustomFoodNote}
          customFoodCost={customFoodCost}
          setCustomFoodCost={setCustomFoodCost}
          customFoodImage={customFoodImage}
          setCustomFoodImage={setCustomFoodImage}
          customFoodTravelDocs={customFoodTravelDocs}
          setCustomFoodTravelDocs={setCustomFoodTravelDocs}
          currency={currency}
        />
      )}
    </>
  );
}
