import DateRangePickerModal from '../../DateRangePickerModal/DateRangePickerModal';
import TripDetailsHeader from './TripDetailsHeader';
import TripDetailsMainBody from './TripDetailsMainBody';

export default function TripDetailsPageLayout({
  trip,
  tripId,
  daysLength,
  titleDropdownRef,
  titleLastClickRef,
  titleEditing,
  setTitleEditing,
  titleEditValue,
  setTitleEditValue,
  titleDisplay,
  titleDropdownOpen,
  setTitleDropdownOpen,
  onCommitTripTitle,
  onShareTrip,
  onPublishTrip,
  onEditPublishedContent,
  onSetCoverPage,
  onDuplicateTrip,
  onRequestDeleteTrip,
  spent,
  currency,
  exchangeRates,
  onBudgetDetailsClick,
  onOpenWhereModal,
  displayDatesLabel,
  onOpenDateModal,
  currencyOptions,
  loadExchangeRates,
  onOpenCurrencyModal,
  setNotesModalOpen,
  onOpenRouteIdeas,
  viewMode,
  setViewMode,
  visibleDays,
  days,
  tripDestination,
  tripExpenseItems,
  openDayMenuKey,
  setOpenDayMenuKey,
  dayColors,
  setDayColors,
  dayColorPickerDay,
  setDayColorPickerDay,
  dayTitles,
  setDayTitle,
  getDayColumnWidth,
  beginDayColumnResize,
  displayStart,
  displayEnd,
  setDateRange,
  setOptimizeRouteDay,
  setOptimizeRouteStartId,
  setOptimizeRouteEndId,
  setOptimizeRouteModalOpen,
  setMapDayFilterSelected,
  setMapDayFilterOpen,
  skipExpenseSaveToastUntilRef,
  setTripExpenseItems,
  setDayTitles,
  setDayColumnWidths,
  showInAppNotice,
  openInternalItemOverview,
  handleImageError,
  transportModeBySegment,
  setTransportModeBySegment,
  openTravelDropdownKey,
  setOpenTravelDropdownKey,
  travelTimeCache,
  setTravelTimeCache,
  setEditPlaceItem,
  setPublicTransportSegment,
  setPublicTransportModalOpen,
  setAddSheetFromCalendar,
  setAddSheetDay,
  setAddSheetAnchor,
  tripDetailsMapPanelProps,
  calendarScrollLeft,
  setCalendarScrollLeft,
  calendarTimelineRef,
  calendarDragOverDayNum,
  setCalendarDragOverDayNum,
  handleCalendarDayDragOver,
  handleCalendarDayDrop,
  calendarDraggingItemId,
  calendarResizingItemId,
  handleCalendarDragStart,
  handleCalendarDragEnd,
  handleCalendarResizeStart,
  kanbanDraggingDayNum,
  kanbanDragOverDayNum,
  handleKanbanDayDragStart,
  handleKanbanDayDragEnter,
  handleKanbanDayDragEnd,
  handleKanbanDayDrop,
  dateModalOpen,
  applyDateRange,
  setDateModalOpen,
}) {
  return (
    <>
      <TripDetailsHeader
        trip={trip}
        tripId={tripId}
        daysLength={daysLength}
        titleDropdownRef={titleDropdownRef}
        titleLastClickRef={titleLastClickRef}
        titleEditing={titleEditing}
        setTitleEditing={setTitleEditing}
        titleEditValue={titleEditValue}
        setTitleEditValue={setTitleEditValue}
        titleDisplay={titleDisplay}
        titleDropdownOpen={titleDropdownOpen}
        setTitleDropdownOpen={setTitleDropdownOpen}
        onCommitTripTitle={onCommitTripTitle}
        onShareTrip={onShareTrip}
        onPublishTrip={onPublishTrip}
        onEditPublishedContent={onEditPublishedContent}
        onSetCoverPage={onSetCoverPage}
        onDuplicateTrip={onDuplicateTrip}
        onRequestDeleteTrip={onRequestDeleteTrip}
        spent={spent}
        currency={currency}
        exchangeRates={exchangeRates}
        onBudgetDetailsClick={onBudgetDetailsClick}
        onOpenWhereModal={onOpenWhereModal}
        displayDatesLabel={displayDatesLabel}
        onOpenDateModal={onOpenDateModal}
        currencyOptions={currencyOptions}
        loadExchangeRates={loadExchangeRates}
        onOpenCurrencyModal={onOpenCurrencyModal}
        onOpenNotesModal={() => setNotesModalOpen(true)}
        onOpenRouteIdeas={onOpenRouteIdeas}
        viewMode={viewMode}
        setViewMode={setViewMode}
      />

      <TripDetailsMainBody
        viewMode={viewMode}
        visibleDays={visibleDays}
        days={days}
        tripDestination={tripDestination}
        tripExpenseItems={tripExpenseItems}
        currency={currency}
        exchangeRates={exchangeRates}
        openDayMenuKey={openDayMenuKey}
        setOpenDayMenuKey={setOpenDayMenuKey}
        dayColors={dayColors}
        setDayColors={setDayColors}
        dayColorPickerDay={dayColorPickerDay}
        setDayColorPickerDay={setDayColorPickerDay}
        dayTitles={dayTitles}
        setDayTitle={setDayTitle}
        getDayColumnWidth={getDayColumnWidth}
        beginDayColumnResize={beginDayColumnResize}
        displayStart={displayStart}
        displayEnd={displayEnd}
        setDateRange={setDateRange}
        setOptimizeRouteDay={setOptimizeRouteDay}
        setOptimizeRouteStartId={setOptimizeRouteStartId}
        setOptimizeRouteEndId={setOptimizeRouteEndId}
        setOptimizeRouteModalOpen={setOptimizeRouteModalOpen}
        setMapDayFilterSelected={setMapDayFilterSelected}
        setMapDayFilterOpen={setMapDayFilterOpen}
        skipExpenseSaveToastUntilRef={skipExpenseSaveToastUntilRef}
        setTripExpenseItems={setTripExpenseItems}
        setDayTitles={setDayTitles}
        setDayColumnWidths={setDayColumnWidths}
        showInAppNotice={showInAppNotice}
        openInternalItemOverview={openInternalItemOverview}
        handleImageError={handleImageError}
        transportModeBySegment={transportModeBySegment}
        setTransportModeBySegment={setTransportModeBySegment}
        openTravelDropdownKey={openTravelDropdownKey}
        setOpenTravelDropdownKey={setOpenTravelDropdownKey}
        travelTimeCache={travelTimeCache}
        setTravelTimeCache={setTravelTimeCache}
        setEditPlaceItem={setEditPlaceItem}
        setPublicTransportSegment={setPublicTransportSegment}
        setPublicTransportModalOpen={setPublicTransportModalOpen}
        setAddSheetFromCalendar={setAddSheetFromCalendar}
        setAddSheetDay={setAddSheetDay}
        setAddSheetAnchor={setAddSheetAnchor}
        tripDetailsMapPanelProps={tripDetailsMapPanelProps}
        calendarScrollLeft={calendarScrollLeft}
        setCalendarScrollLeft={setCalendarScrollLeft}
        calendarTimelineRef={calendarTimelineRef}
        calendarDragOverDayNum={calendarDragOverDayNum}
        setCalendarDragOverDayNum={setCalendarDragOverDayNum}
        handleCalendarDayDragOver={handleCalendarDayDragOver}
        handleCalendarDayDrop={handleCalendarDayDrop}
        calendarDraggingItemId={calendarDraggingItemId}
        calendarResizingItemId={calendarResizingItemId}
        handleCalendarDragStart={handleCalendarDragStart}
        handleCalendarDragEnd={handleCalendarDragEnd}
        handleCalendarResizeStart={handleCalendarResizeStart}
        kanbanDraggingDayNum={kanbanDraggingDayNum}
        kanbanDragOverDayNum={kanbanDragOverDayNum}
        handleKanbanDayDragStart={handleKanbanDayDragStart}
        handleKanbanDayDragEnter={handleKanbanDayDragEnter}
        handleKanbanDayDragEnd={handleKanbanDayDragEnd}
        handleKanbanDayDrop={handleKanbanDayDrop}
      />

      <DateRangePickerModal
        open={dateModalOpen}
        start={displayStart}
        end={displayEnd}
        displayStartForMonth={displayStart}
        onApply={applyDateRange}
        onClose={() => setDateModalOpen(false)}
        title="When"
      />
    </>
  );
}
